config/routes.rb
Webblog::Application.routes.draw do
  
  root :to => 'static#home'
  
  get 'about' => 'static#about', as: 'about'
  
  get 'drafts' => 'posts#drafts', as: 'drafts'
  
  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  self.per_page = 2
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  self.per_page = 2
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:author,:message))
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.paginate(page: params[:page])
    @comment = Comment.new
  end
  
  def index
    @posts = Post.where(draft: false).paginate(page: params[:page])
  end
  
  def new
    @post = Post.new
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def create
    @post = Post.new(getParams)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(getParams)
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  
  def drafts
    @posts = Post.where(draft: true).paginate(page: params[:page])
    render 'index'
  end
  
  private
  
  def getParams
    params[:post].permit(:title,:content,:draft)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  
  def home
    
  end
  
  def about
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/comments/_comment.html.erb
<p>
	<strong><%= comment.author%></strong>
	says
	<em><%= comment.message%></em>	
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f|%>

	<p>Author: <%= f.text_field :author%></p>
	<p>Message: <%= f.text_area :message%></p>
	<p><%= f.submit 'Add comment'%></p>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webblog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to 'Home', root_path%> | 
<%= link_to 'Blog', posts_path%> | 
<%= link_to 'Draft', drafts_path%> | 
<%= link_to 'About', about_path%>
<br />
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%>

	Title: <%= f.text_field :title%><br />
	Content: <%= f.text_area :content%><br />
	Draft: <%= f.check_box :draft%><br />
	
	<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form'%>

app/views/posts/index.html.erb
<%= link_to 'New post', new_post_path%>

<table>
	<tr>
		<th>Title</th>
	</tr>
	<% @posts.each do |post|%>
		<tr>
			<td><%= link_to post.title, post%></td>
		</tr>
	<% end %>
</table>

<%= will_paginate @posts%>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form'%>

app/views/posts/show.html.erb
<h1><%= @post.title%></h1>
<p><%= @post.content%></p>

<%= link_to 'Back', posts_path%> - 
<%= link_to 'Edit', edit_post_path(@post)%> - 
<%= link_to 'Delete', @post, method: 'delete'%>

<%= render @comments%>

<%= will_paginate @comments%>
<%= render 'comments/form'%>